version: "3.9"

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "su -c 'pg_isready -U postgres' postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5433:5432"

  minio:
    image: minio/minio:latest
    volumes:
      - ./s3/data:/data
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_PANEL_PORT}:9001
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: false
    command: server --console-address ":9001" /data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbitmq:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - backend

  keycloak:
    image: keycloak/keycloak:26.3.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: temporary-admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8155:8080"
    command:
      - start-dev
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: /celery
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

  backend:
    container_name: vkr-check-backend
    build: ./backend
    restart: unless-stopped
    command: uvicorn src.main:app --host=0.0.0.0 --port=8000
    env_file:
      - ./backend/.env.production
    depends_on:
      - minio
      - postgres
      - rabbitmq
    ports:
      - "8000:8000"
    networks:
      - backend

  worker:
    container_name: vkr-check-worker
    build: ./worker
    restart: unless-stopped
    env_file:
      - ./worker/.env.production
    depends_on:
      - minio
      - postgres
      - rabbitmq
    networks:
      - backend

  frontend:
    container_name: vkr-check-frontend
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - backend

  nginx:
    container_name: vkr-check-nginx
    image: nginx:stable-alpine
    restart: on-failure
    ports:
      - "4200:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - frontend
      - backend                                               
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  keycloak_data:
  rabbitmq_data: