version: '3.8'

services:
  ollama-server:
    profiles: ["ollama"]
    build: 
      context: ./ollama/${MODEL_DIR}
      dockerfile: Dockerfile
    container_name: ollama-server
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_GPU_MEMORY_FRACTION=0.8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '4gb'
    volumes:
      - ./ollama/${MODEL_DIR}/Modelfile:/app/Modelfile
    ports:
      - "11434:11434"
    networks:
      - llm_shared_network
